master:
  ## home config
  #ip: jdbc:mysql://192.168.1.161:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
  ## company config
  ip: jdbc:mysql://192.168.18.32:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
slave:
  ## home config
  #ip: jdbc:mysql://192.168.1.162:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
  ## company config
  ip: jdbc:mysql://192.168.18.33:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
#########################################################################################################################################
server:
  context-path: /mail-producer
  port: 8001
  tomcat:
    uri-encoding: UTF-8

## Spring config
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    username: 15210296080@163.com
    password: zhao65525070042

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: ${master.ip}
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
  slave:
    url: ${slave.ip}
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true

mybatis:
  type-aliases-package: com.zoro.mail
  mapper-locations: classpath:com/zoro/mail/mapping/*.xml

logging:
  level:
    tk.mybatis: TRACE

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql