server:
  context-path: /mail-producer
  port: 8001
  tomcat:
    uri-encoding: UTF-8

## Spring\u914D\u7F6E
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  redis:
#    pool:
#      min-idle: 100
#      max-idle: 100
#      max-wait: -1
#      max-active: 1000
#    timeout: 6000
#    cluster:
#      max-redirects: 1000
#      nodes:
#        - 192.168.1.117:7001
#        - 192.168.1.117:7002
#        - 192.168.1.117:7003
#        - 192.168.1.117:7004
#        - 192.168.1.117:7005
#        - 192.168.1.117:7006

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    username: zhao65525@163.com
    password: zhaoguangfu
      mail:
        smtp:
          auth: true
          timeout: 30000
druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: jdbc:mysql://192.168.1.31:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=converToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 1
#    maxIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
  slave:
    url: jdbc:mysql://192.168.1.32:3306/mail?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=converToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 1
#    maxIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true

mybatis:
  type-aliases-package: com.zoro.mail
  mapper-locations: classpath:com/zoro/mail/mapping/*.xml

logging:
  level:
    tk.mybatis: trace

#mapper:
#  mappers:
#    - com.xxx.xxx.BaseMapper
#  not-empty: false
#  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql